-- =============================================================================
-- challenge_waitlist — 마감·모집예정 챌린지의 '오픈 알림 받기' 명단 (2026-07-30)
--
-- 배경: 챌린지 4개 중 2개가 '마감'인데 관심을 남길 자리가 없어, 상세페이지에서
--       전·후 오디오 14개와 후기 55개를 다 보고 마음먹은 사람이 "다음 회차를
--       기다려주세요!" 경고창만 보고 그냥 나갔다. 그 수요를 받는 테이블.
--
-- ⚠️ applications 에 섞지 않는 이유(섞자는 안은 명시적으로 기각):
--   · 중복 신청 트리거(MC002)·정원 트리거가 대기 명단을 '신청'으로 세어 버린다
--   · admin '신청자 현황' 목록·CSV·매출 집계가 오염된다
--   대기 명단은 '아직 안 산 사람'이므로 신청과 같은 표에 있을 수 없다.
--
-- 적용: Supabase SQL Editor 에서 실행(이 레포는 자동 마이그레이션이 없다).
-- 미적용 시 degrade: '오픈 알림 받기' 제출이 실패하고 사용자에게 안내가 뜬다.
--                    챌린지 신청·결제 등 나머지 흐름은 영향 없음.
-- =============================================================================

create table if not exists public.challenge_waitlist (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  challenge   text not null,          -- voice / expression / spinning / answer
  name        text not null,
  phone       text not null,
  member_id   uuid references public.members(id) on delete set null,
  -- 'waiting' = 연락 전, 'notified' = 오픈 안내 완료(admin 에서 체크)
  status      text not null default 'waiting',
  notified_at timestamptz,
  -- 개인정보 수집·이용 동의 기록(법적 필수 — 화면의 필수 체크와 한 쌍)
  agreed_at     timestamptz not null default now(),
  terms_version text
);

comment on table public.challenge_waitlist is
  '챌린지 오픈 알림 대기 명단(비회원 포함). 이름·전화 = 개인정보. RLS 로 SELECT 는 관리자만.';
comment on column public.challenge_waitlist.status is
  'waiting=연락 전 / notified=오픈 안내 완료. 연락이 끝난 명단은 파기 권장(개인정보 최소보유).';

-- 같은 사람이 같은 챌린지를 두 번 남기지 못하게.
-- ⚠️ 전화번호는 표기가 제각각('010-1234-5678' / '01012345678')이라 숫자만 뽑아 비교한다.
--    regexp_replace 는 IMMUTABLE 이라 인덱스 식으로 쓸 수 있다.
-- ⚠️ 클라이언트는 이 제약 위반(23505)을 '이미 신청되어 있어요'로 안내한다 — 에러로 띄우지 말 것.
create unique index if not exists challenge_waitlist_uq
  on public.challenge_waitlist (challenge, regexp_replace(phone, '\D', '', 'g'));

create index if not exists challenge_waitlist_lookup
  on public.challenge_waitlist (challenge, status, created_at desc);

alter table public.challenge_waitlist enable row level security;

-- INSERT — 누구나(비회원도 남길 수 있어야 한다).
-- ⚠️ member_id 는 null 또는 본인 uid 만 — 타인 계정으로 위장 등록 차단(applications 와 같은 방어).
drop policy if exists "waitlist insert public" on public.challenge_waitlist;
create policy "waitlist insert public" on public.challenge_waitlist
  for insert to anon, authenticated
  with check (member_id is null or member_id = auth.uid());

-- SELECT — 관리자만.
-- ⚠️ 본인 조회조차 열지 않는다: 전화번호로 명단을 조회할 수 있는 창구를 만들면
--    "이 사람이 몬크에 관심을 남겼는지"를 번호만으로 캐낼 수 있다(중복 신청 가드에서
--    비회원 사전 조회를 막은 것과 같은 이유).
drop policy if exists "waitlist select admin" on public.challenge_waitlist;
create policy "waitlist select admin" on public.challenge_waitlist
  for select to authenticated
  using (public.is_admin());

drop policy if exists "waitlist update admin" on public.challenge_waitlist;
create policy "waitlist update admin" on public.challenge_waitlist
  for update to authenticated
  using (public.is_admin()) with check (public.is_admin());

drop policy if exists "waitlist delete admin" on public.challenge_waitlist;
create policy "waitlist delete admin" on public.challenge_waitlist
  for delete to authenticated
  using (public.is_admin());

-- 검증(실행 후):
--   1) 로그아웃 상태에서 조회가 0 건인지 —
--      curl -sI "https://apzwauiumhmsvrgffjis.supabase.co/rest/v1/challenge_waitlist?select=id" \
--        -H "apikey: <anon key>" -H "Prefer: count=exact"   →  Content-Range: */0
--   2) 상세페이지(보신각) '오픈 알림 받기' 제출이 접수되는지.
--   3) 같은 번호로 한 번 더 제출하면 '이미 신청되어 있어요' 안내가 뜨는지.
--   4) admin '오픈 알림' 탭에서 명단이 보이고 '연락 완료' 체크·삭제가 되는지.
