-- =============================================================================
-- recruit_tips — 채용 캘린더 제보함 (2026-08-04)
--
-- 배경: 채용 캘린더(recruit_rounds)는 연구진이 손으로 채운다. 날짜가 틀리거나
--       빠진 공채를 가장 먼저 아는 사람은 그 전형을 방금 치른 학생이다.
--       서가 화면 아래에서 한 줄로 받아 admin '채용 캘린더' 탭에서 읽고 고친다.
--
-- ⚠️ recruit_rounds 에 직접 쓰게 하지 않는다 — 제보는 '확인 전 주장'이고
--    회차는 '연구진이 확인한 기록'이다. 검수 없이 합치면 화면의 모든 계산이
--    출처를 잃는다(학생 화면 문구: "공고와 합격자 제보를 바탕으로 연구진이 기록").
--
-- ⚠️ 개인정보를 묻지 않는다 — 이름·연락처 칸이 없다(challenge_waitlist 와 다르다).
--    로그인 상태면 member_id 만 붙는다(연구진이 되물을 수 있게. admin 만 읽는다).
--
-- 적용: Supabase SQL Editor 에 붙여넣고 Run. idempotent — 재실행 안전.
-- 미적용 시 degrade: 제보 보내기가 실패하고 '제보함 준비가 아직 안 됐어요'가 뜬다.
--                    캘린더 목록·나머지 화면은 영향 없음.
-- 선행: 20260703120000(members·is_admin)
-- =============================================================================

create table if not exists public.recruit_tips (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  -- 슬러그(kal·asiana…). 모르거나 목록에 없으면 null — 강제하지 않는다
  airline     text,
  -- 제보 본문. 학생이 아는 대로 자유롭게 적는다
  body        text not null,
  -- 어디서 알았나(공고 링크·'제가 지원했어요'). 선택
  source      text,
  -- 로그인 상태였을 때만. 비회원 제보도 받는다
  member_id   uuid references public.members(id) on delete set null,
  -- new = 안 읽음 / done = 반영·확인 완료(admin 에서 체크)
  status      text not null default 'new',
  handled_at  timestamptz
);

comment on table public.recruit_tips is
  '채용 캘린더 제보함. 확인 전 주장이며 recruit_rounds 와 별개다. 읽기는 관리자만.';

-- 길이·상태 상한. ⚠️ 공개 INSERT 창구라 본문 길이를 DB 가 막는다(브라우저 검사만 믿지 않는다)
alter table public.recruit_tips drop constraint if exists recruit_tips_sane;
alter table public.recruit_tips add constraint recruit_tips_sane check (
      char_length(btrim(body)) between 5 and 1000
  and (airline is null or char_length(airline) <= 30)
  and (source  is null or char_length(source)  <= 300)
  and status in ('new', 'done')
);

-- admin 은 '안 읽은 것부터 최신순'으로 읽는다
create index if not exists recruit_tips_inbox
  on public.recruit_tips (status, created_at desc);

-- =============================================================================
-- RLS — 넣기는 누구나, 보기는 관리자만
-- =============================================================================
alter table public.recruit_tips enable row level security;

-- INSERT — 비회원도 남길 수 있어야 한다(제보하는 사람 대부분이 로그인 전이다).
-- ⚠️ member_id 는 null 또는 본인 uid 만(타인 계정 위장 차단 — challenge_waitlist 와 같은 방어).
-- ⚠️ status·handled_at 을 고정한다 — 넣는 쪽이 '처리 완료'로 위장해 들어와 숨지 못하게.
drop policy if exists recruit_tips_insert_public on public.recruit_tips;
create policy recruit_tips_insert_public on public.recruit_tips
  for insert to anon, authenticated
  with check (
    (member_id is null or member_id = auth.uid())
    and status = 'new' and handled_at is null
  );

-- SELECT — 관리자만. ⚠️ 본인 조회도 열지 않는다(제보 본문에 남의 전형 이야기가 섞인다).
drop policy if exists recruit_tips_select_admin on public.recruit_tips;
create policy recruit_tips_select_admin on public.recruit_tips
  for select to authenticated using (public.is_admin());

drop policy if exists recruit_tips_update_admin on public.recruit_tips;
create policy recruit_tips_update_admin on public.recruit_tips
  for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists recruit_tips_delete_admin on public.recruit_tips;
create policy recruit_tips_delete_admin on public.recruit_tips
  for delete to authenticated using (public.is_admin());

-- 검증(실행 후):
--   1) 로그아웃 상태 조회가 0 건인지 —
--      curl -sI "https://apzwauiumhmsvrgffjis.supabase.co/rest/v1/recruit_tips?select=id" \
--        -H "apikey: <anon key>" -H "Prefer: count=exact"   →  Content-Range: */0
--   2) lab-shelf.html?shelf=calendar 아래 '일정 알려주기'로 보내면 접수되는지.
--   3) admin '채용 캘린더' 탭 맨 위 제보함에 그 글이 뜨고 '확인함'·삭제가 되는지.
