-- =============================================================================
-- game_reports — 역량검사 게임 연습장 오류 제보함 (2026-08-25)
--
-- 배경: 게임 버그 제보를 처음엔 카카오톡 문의로 받으려 했으나 오너가 기각 —
--       "카톡은 상담 문의에 관련된 내용이라 섞이면 안돼". 그래서 홈페이지 자체에
--       내용이 남는 테이블로 받는다(games.html 하단 제보 폼).
--
-- ⚠️ 개인정보를 일부러 안 받는다: 연락처 칸 없음, 본문(message)뿐.
--    답변이 필요한 문의는 상담 창구 몫이고, 여기는 버그 기록함이다.
--    (전화번호 조회 창구 금지 원칙과 같은 결 — CLAUDE.md '개인정보' 절)
--
-- 적용: Supabase SQL Editor 에서 실행(이 레포는 자동 마이그레이션이 없다).
-- 미적용 시 degrade: 제보 전송이 실패하고 "준비 중" 안내가 뜬다.
--                    게임 플레이·점수 기록 등 나머지는 영향 없음.
-- =============================================================================

create table if not exists public.game_reports (
  id         bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  game       text not null default '',   -- 게임 id(nback·rps·…) 또는 '' = 페이지 전체
  mode       text not null default '',   -- 제보 당시 모드(practice/real/부분 연습 키)
  message    text not null,
  ua         text not null default '',   -- 브라우저 식별용 userAgent 요약(재현에 필요)
  member_id  uuid references public.members(id) on delete set null
);

comment on table public.game_reports is
  '역량검사 게임 연습장 버그 제보(비회원 포함). 연락처 없음 — 본문만. SELECT 는 관리자만.';

create index if not exists game_reports_recent
  on public.game_reports (created_at desc);

alter table public.game_reports enable row level security;

-- INSERT — 누구나(게임이 비회원 공개라 제보도 비회원이 남길 수 있어야 한다).
-- ⚠️ 길이 제한을 정책에 박는다 — 익명 쓰기라 서버가 유일한 방어선이다.
-- ⚠️ member_id 는 null 또는 본인 uid 만(waitlist 와 같은 위장 등록 차단).
drop policy if exists "game_reports insert public" on public.game_reports;
create policy "game_reports insert public" on public.game_reports
  for insert to anon, authenticated
  with check (
    char_length(message) between 5 and 2000
    and char_length(game) <= 40
    and char_length(mode) <= 40
    and char_length(ua) <= 300
    and (member_id is null or member_id = auth.uid())
  );

-- SELECT/UPDATE/DELETE — 관리자만.
drop policy if exists "game_reports select admin" on public.game_reports;
create policy "game_reports select admin" on public.game_reports
  for select to authenticated
  using (public.is_admin());

drop policy if exists "game_reports delete admin" on public.game_reports;
create policy "game_reports delete admin" on public.game_reports
  for delete to authenticated
  using (public.is_admin());

-- 검증(실행 후):
--   1) 로그아웃 상태에서 조회가 0 건인지 —
--      curl -sI "https://apzwauiumhmsvrgffjis.supabase.co/rest/v1/game_reports?select=id" \
--        -H "apikey: <anon key>" -H "Prefer: count=exact"   →  Content-Range: */0
--   2) games.html 하단 '게임 오류 제보'에서 제출 → "접수됐어요" 안내가 뜨는지.
--   3) Supabase Table Editor 에서 그 행이 보이는지(당분간 확인 창구 — admin 탭은 추후).
