-- =============================================================================
-- applications 테이블 RLS 하드닝 (개인정보 보호법 안전조치 — 최우선 보안)
-- 배경: applications 는 Supabase 콘솔에서 수동 생성돼 레포 마이그레이션에 RLS 선언이
--       없었다. 이 테이블에는 신청자 이름·전화번호·환급 계좌가 담기므로, RLS 가
--       꺼져 있으면 공개 anon key 만으로 전체 신청자 개인정보가 조회될 수 있다.
-- 정책 요약:
--   INSERT — 누구나(비회원 신청 유지). 단 member_id 는 null 또는 본인 uid 만 허용
--            (타인 계정으로 위장 신청 차단).
--   SELECT — 관리자 전체 + 회원 본인 것(member_id = auth.uid())만.
--   UPDATE/DELETE — 관리자만 (admin.html 입금/환급 토글·삭제).
-- 적용: Supabase SQL Editor 에서 이 파일을 실행하면 됨(이 레포는 자동 마이그레이션 없음).
-- 검증(실행 후):
--   1) 로그아웃 상태(시크릿 창)에서 아래를 실행해 0 건인지 확인:
--      curl -s -I "https://apzwauiumhmsvrgffjis.supabase.co/rest/v1/applications?select=id" \
--        -H "apikey: <anon key>" -H "Prefer: count=exact"   →  Content-Range: */0
--   2) apply.html 에서 비회원 신청이 여전히 접수되는지 확인.
--   3) admin.html 신청 관리 탭이 정상 조회·수정되는지 확인.
-- =============================================================================

-- 콘솔 생성 테이블 문서화용(운영 DB 에는 이미 존재하므로 no-op).
-- 새 환경에 세울 때만 실제 생성된다. 운영 스키마와 다르면 운영 쪽이 기준.
create table if not exists public.applications (
  id             bigint generated by default as identity primary key,
  created_at     timestamptz not null default now(),
  name           text not null,
  phone          text not null,
  refund_account text not null,
  challenges     jsonb,
  total_price    integer,
  paid           boolean not null default false,
  refunded       boolean not null default false,
  member_id      uuid references public.members(id) on delete set null
);

comment on table public.applications is
  '챌린지 신청(비회원 포함). 이름·전화·환급계좌 = 개인정보. RLS 로 SELECT 는 관리자·본인만.';

-- member_id 컬럼이 없던 초기 환경 대비(운영엔 이미 존재).
alter table public.applications add column if not exists member_id uuid references public.members(id) on delete set null;

-- ── RLS 활성화 ───────────────────────────────────────────────────────────────
alter table public.applications enable row level security;

-- 재실행 안전을 위해 기존 정책 제거 후 재생성
drop policy if exists applications_insert_public on public.applications;
drop policy if exists applications_select_own    on public.applications;
drop policy if exists applications_admin_all     on public.applications;

-- INSERT: 비회원(anon)·회원(authenticated) 모두 신청 가능.
-- 단 member_id 는 비우거나 본인 uid 만 — anon 은 auth.uid() 가 null 이라 자동으로 null 만 가능.
create policy applications_insert_public on public.applications
  for insert
  to anon, authenticated
  with check (member_id is null or member_id = auth.uid());

-- SELECT: 회원은 자기 신청만 (mypage '내 신청내역')
create policy applications_select_own on public.applications
  for select
  to authenticated
  using (member_id = auth.uid());

-- 관리자: 전체 조회·수정·삭제 (admin.html 신청 관리)
create policy applications_admin_all on public.applications
  for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());
